### ISSUE TITLE
import gmql failed

### ISSUE THREAD

**Issue by TomohiroUchida** [DEIB-GECO/PyGMQL#29]
I cloned git , and tryed to import gmql. 
I tried it on centos7 and centos8 and ubuntu18.04 .
I also tried it on python 3.7.4 and python 3.6.8.
When I tried to run it I got:

```
$ echo $JAVA_HOME
/usr/java/default
$ which java
/usr/java/default/bin/java

$ pip list |grep gmql
gmql                          0.1.1
$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/lib/python3.7/site-packages/gmql/__init__.py", line 31, in <module>
    __init()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/gmql/__init__.py", line 27, in __init
    __init_managers()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/gmql/managers.py", line 302, in init_managers
    __check_dependencies()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/gmql/managers.py", line 288, in __check_dependencies
    __gmql_jar_path = __dependency_manager.resolve_dependencies()
  File "/usr/local/miniconda3/lib/python3.7/site-packages/gmql/FileManagment/DependencyManager.py", line 126, in resolve_dependencies
    resp = self._parse_dependency_info_fromstring(resp_text)
  File "/usr/local/miniconda3/lib/python3.7/site-packages/gmql/FileManagment/DependencyManager.py", line 75, in _parse_dependency_info_fromstring
    tree = ET.ElementTree(ET.fromstring(s))
  File "/usr/local/miniconda3/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 12, column 4
>>>
```

I think something changed external environment used for initialization.
Please check it.
Best regards.

**Comment by lucananni93** [comment]
Thanks for your interest in our package.

There was an issue with the availability for download of the Scala backend of the library, which now should be fixed.

Please check if `import gmql` works now.
